### ISSUE TITLE
Could you provide a release built apk?

### ISSUE THREAD

**Issue by YxMingY** [HyperLife1119/Explore#1]
I cat not build it.

**Comment by HyperLife1119** [comment]
The project has been abandoned.

**Comment by HyperLife1119** [comment]
And it is unfinished, and there are still loopholes.

**Comment by YxMingY** [comment]
Ah, it seems that you had already been able to use this github function( ˃̶̤́ ꒳ ˂̶̤̀ )

**Comment by HyperLife1119** [comment]
You are right.
